#!/bin/bash

#$ -M zvincent@nd.edu # Email address for job notification
#$ -m abe             # Send mail when job begins, ends and aborts
#$ -pe smp 2
#$ -q gpu             # Specify queue
#$ -l gpu_card=1
#$ -o ~/log/
#$ -e ~/log/
#$ -N asl-train     # Specify job name

conda activate asl
python3 train.py
