#!/bin/bash

#$ -M zvincent@nd.edu # Email address for job notification
#$ -m abe             # Send mail when job begins, ends and aborts
#$ -pe smp 2          # Specify parallel environment and legal core size
#$ -q gpu             # Specify queue
#$ -o ~/log/
#$ -e ~/log/
#$ -N asl-train     # Specify job name

conda activate asl
python3 do-train.py
